### ISSUE TITLE
Comics plasmoid

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-paperkuts#28]
![desktop](https://cloud.githubusercontent.com/assets/840070/3637056/ae8888a8-0ff2-11e4-919e-a9ba499592b0.png)

**Comment by star-buck** [comment]
How do I set a comic to show up in the plasmoid?
I added many comics from GHNS, but none showed up (in KCI 20150313)?

**Comment by notmart** [comment]
It's supposed to add the comics in the config dialog as a list of checkboxes right after they are just like the plasma4 version did.

I tested on the ISO: there seems to be a couple of problems there:
- the package "kpackagetool5" is not installed by default, installing it becomes possible to install comic providers

- then the comics themselves seems to still not work: the dataengine uses the kross framework, which seems to not be installed. I added an explicit dependency to it in the kdeplasma-addons repo,let's see if it will make it build correctly

**Comment by apachelogger** [comment]
revised dependencies.
libkf5package recommends (default install, but can be opted out of): kpackagetool5
libkf5krosscore recommends (as above: kross
plasma-widgets-addons: depends on kpackagetool5
plasma-dataengines-addons: depends on kross

**Comment by star-buck** [comment]
back and works great :)
