### ISSUE TITLE
[kio-sysinfo]: plasma5 version detection and page reload

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-paperkuts#37]

**Comment by shadeslayer** [comment]
Should be fixed with https://github.com/netrunner/kio-sysinfo/commit/5922d40f4a069ea269011929c521cce8f1dcadd2 and https://github.com/netrunner/kio-sysinfo/commit/95d32237db00b68d4affa4f2e10e066f090d72fa

**Comment by star-buck** [comment]
Looks good so far, here is screenshot:
![kio-sysinfo](https://cloud.githubusercontent.com/assets/840070/6047311/2e56194e-aca9-11e4-8ab8-479db6a1c4d3.png)

Could you switch again right and left side informations, so "online" and "disk status" go to the right side and all the others to left?
Then fix the style extending to the right side for bigger resolutions, thanks.

**Comment by shadeslayer** [comment]
Sure, I'll get it done :)

**Comment by shadeslayer** [comment]
Done, fixes in netrunner/kio-sysinfo

**Comment by star-buck** [comment]
awesome works!
