### ISSUE TITLE
[folderview]: select icons via rubberband capture sooner, like after covering 1/3 of the icon or immediatly when touching (like windows or mac) instead of half

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-paperkuts#38]

**Comment by eikehein** [comment]
Hm OK, I personally prefer half but I've heard this from several people now so I guess I'll change it :)

**Comment by eikehein** [comment]
Done for 5.2.1: http://commits.kde.org/plasma-desktop/7aa4995ff5f018a59073c41be647ddf49d235de1
