### ISSUE TITLE
[wallpaper settings]: if no metadata file is found (just a single image) remove the "by Unkown" text from mouse over

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-paperkuts#40]

**Comment by mck182** [comment]
Patch here https://git.reviewboard.kde.org/r/122622/

**Comment by mck182** [comment]
Done. Will be in Plasma 5.2.1 -- http://commits.kde.org/plasma-workspace/5d552d08a3ebe6ec4a8f59e0a91a510c1d9a51e2
